server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_prod?useUnicode=true&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8
    # root
    username: MyEnc({btTSNb3PH7saU2yQ7FeCsQ==})
    # root
    password: MyEnc({VuLn6kkmZXt1402C9w9xUA==})
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      key-prefix: admin_prod
      time-to-live: 60s
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # root
    password: MyEnc({eCOS8Sk9b/kWt2FK0QFA9g==})
    jedis.pool:
      max-active: 8
      max-wait: -1ms
      max-idle: 8
      min-idle: 0

logging:
  level.com.zoctan.api: warn

jwt:
  admin-expire-time: 7d
  wechat-expire-time: 30d
  claim-key-auth: auth
  header: Authorization
  token-type: Bearer
